### ISSUE TITLE
Must install the image with the pod

### ISSUE THREAD

**Issue by Lascorbe** [jberlana/JBWhatsAppActivity#3]
The image "whatsapp@2x.png" is not installing with the pod (Pod is copying it but not installing). Could you provide the podspec file to fix it?

Thanks.

**Comment by jberlana** [comment]
Hi Luis,

this is the podspec, am I missing something?

```
Pod::Spec.new do |s|
  s.name     = 'JBWhatsAppActivity'
  s.version  = '1.0'
  s.summary  = 'JBWhatsAppActivity is a UIActivity subclass that provides an “Share in WhatsApp" action to a UIActivityViewController.'
  s.license  = { :type => 'MIT', :file => 'License.md' }
  s.homepage = 'https://github.com/jberlana/JBWhatsAppActivity'
  s.author   = { 'Javier Berlana' => 'jberlana@gmail.com' }
  s.source   = { :git => 'https://github.com/jberlana/JBWhatsAppActivity.git', :tag => '1.0' }
  s.platform = :ios
  s.source_files = 'JBWhatsAppActivity/*'
  s.requires_arc = true
end
```

**Comment by jberlana** [comment]
Ok, I just updated the podspect and submit a pull request with:

```
...
s.source_files = 'JBWhatsAppActivity/*.{h,m}'
s.resource     = 'JBWhatsAppActivity/whatsapp@2x.png'
```

https://github.com/jberlana/Specs/commit/c419da1985dd17fb3bced983a1b13880b2da86e4

**Comment by Lascorbe** [comment]
Great, thanks Javier! Just remember, it's better to create a bundle for resources because of the naming collisions. [Related](http://marker.to/u5vLzc).
